name: Release
on:
  workflow_run:
    workflows:
      - Checks
    branches:
      - master
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26
      - name: Install release-clerk
        run: go install github.com/artem328/release-clerk@19a0cb5b88f1bcd10065608d23ca7a81cffde38f
      - name: Set up git user
        run: |
          git config user.name 'Release Clerk'
          git config user.email 'noreply@localhost'
      - name: Release
        id: release
        run: |
          set -euo pipefail
          
          release-clerk release --format json |
          jq -r '
            {
              version: .Version.SemVer.String,
              tag: .Tag
            }
            | to_entries[]
            | "\(.key)=\(.value)"
          ' >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        run: |
          set -euo pipefail
          
          release-clerk changelog --version "${{ steps.release.outputs.version }}" | 
          gh release create "${{ steps.release.outputs.tag }}" \
            --title "v${{ steps.release.outputs.version }}" \
            --notes-file -
        env:
          GH_TOKEN: ${{ github.token }}
